name: Debricked scan

on: [push, pull_request]

jobs:
    debricked-scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
                  cache: 'gradle'
            - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
            - uses: debricked/actions/scan@v1
              env:
                  DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
